# -*- coding: utf-8 -*-
"""phd_datacleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nd-Jrcfn3RMRFYBXJI6Rauf-1IttQK9v
"""

import pandas as pd
import re

# Read cleaned dataset
df = pd.read_csv("/content/CKD_Cleaned_Dataset (1).csv", dtype=str)

# --------------------------------------------------------
# Convert interval values to numeric values
# --------------------------------------------------------
def convert_interval(value):

    if pd.isna(value):
        return value

    value = str(value).strip()

    # Already numeric
    try:
        return float(value)
    except:
        pass

    # <number
    if value.startswith("<"):
        try:
            return float(value[1:]) / 2
        except:
            return value

    # >=number
    if value.startswith(">="):
        try:
            return float(value[2:]) * 1.10
        except:
            return value

    # number-number
    m = re.match(r'^(-?\d+\.?\d*)-(-?\d+\.?\d*)$', value)

    if m:
        low = float(m.group(1))
        high = float(m.group(2))
        return round((low + high) / 2, 3)

    return value

# --------------------------------------------------------
# Apply conversion
# --------------------------------------------------------
for col in df.columns:
    df[col] = df[col].apply(convert_interval)

# --------------------------------------------------------
# Save dataset
# --------------------------------------------------------
output = "/content/CKD_ML_Ready.csv"

df.to_csv(output, index=False)

print("ML-ready dataset saved as:", output)

from google.colab import files

files.download("/content/CKD_ML_Ready.csv")