# -*- coding: utf-8 -*-
"""updatedresults.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pjTPdJNyl3ztiDNLb_Ht7um0qT8ley44
"""

pip install ctgan imbalanced-learn scikit-learn pandas numpy

!pip install -q sdv

!pip install -q sdv imbalanced-learn

!pip install sdv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sdv.metadata import Metadata
from sdv.single_table import CTGANSynthesizer

from sdv.evaluation.single_table import (
    evaluate_quality,
    run_diagnostic
)

from imblearn.over_sampling import SMOTE

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

file_path = "/content/CKD_ML_Ready.csv"

df = pd.read_csv(file_path)

print("Original Dataset Shape:", df.shape)
print("\nClass Distribution:")
print(df["class"].value_counts())

print("\nDataset Information:")
print(df.info())

# ============================================================
# 4. BASIC DATA CLEANING
# ============================================================

# Remove completely empty rows
df = df.dropna(how="all").reset_index(drop=True)

# Remove duplicate rows
df = df.drop_duplicates().reset_index(drop=True)

# Remove unwanted spaces from object columns
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

print("Dataset after cleaning:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

# ============================================================
# 4. BASIC DATA CLEANING
# ============================================================

# Remove completely empty rows
df = df.dropna(how="all").reset_index(drop=True)

# Remove duplicate rows
df = df.drop_duplicates().reset_index(drop=True)

# Remove unwanted spaces from object columns
for col in df.select_dtypes(include="object").columns:
    df[col] = df[col].astype(str).str.strip()

print("Dataset after cleaning:", df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

# ============================================================
# 5. HANDLE MISSING VALUES
# ============================================================

categorical_columns = df.select_dtypes(include="object").columns
numerical_columns = df.select_dtypes(exclude="object").columns

# Categorical missing values -> mode
for col in categorical_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

# Numerical missing values -> median
for col in numerical_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].median())

print("Missing values after preprocessing:")
print(df.isnull().sum().sum())

# ============================================================
# 6. DEFINE CATEGORICAL COLUMNS
# ============================================================

categorical_columns = [
    "class",
    "grf",
    "stage"
]

print("Categorical Columns:")
print(categorical_columns)

print("\nData Types:")
print(df.dtypes)

# ============================================================
# 7. CREATE SDV METADATA
# ============================================================

metadata = Metadata.detect_from_dataframe(
    data=df,
    table_name="CKD"
)

# Explicitly set categorical columns
for col in categorical_columns:
    metadata.update_column(
        column_name=col,
        sdtype="categorical"
    )

print(metadata)

# ============================================================
# 8. TRAIN CTGAN
# ============================================================

ctgan = CTGANSynthesizer(
    metadata,
    epochs=700,
    batch_size=50,
    verbose=True
)

ctgan.fit(df)

print("CTGAN training completed.")

# ============================================================
# 9. GENERATE 800 SYNTHETIC RECORDS
# ============================================================

synthetic_df = ctgan.sample(num_rows=800)

print("Synthetic Dataset Shape:", synthetic_df.shape)

print("\nSynthetic Dataset:")
display(synthetic_df.head())

print("\nSynthetic Class Distribution:")
print(synthetic_df["class"].value_counts())

# ============================================================
# 10. SAVE SYNTHETIC DATASET
# ============================================================

synthetic_df.to_csv(
    "/content/CKD_CTGAN_800_Synthetic.csv",
    index=False
)

print("800 synthetic records saved.")

# ============================================================
# 11. CTGAN DIAGNOSTIC EVALUATION
# ============================================================

diagnostic_report = run_diagnostic(
    real_data=df,
    synthetic_data=synthetic_df,
    metadata=metadata
)

print(diagnostic_report)

# ============================================================
# 12. CTGAN QUALITY EVALUATION
# ============================================================

quality_report = evaluate_quality(
    real_data=df,
    synthetic_data=synthetic_df,
    metadata=metadata
)

print(quality_report)

quality_score = quality_report.get_score()

print("Overall CTGAN Quality Score:", quality_score)

# ============================================================
# 13. COMPARE CLASS DISTRIBUTION
# ============================================================

original_class = df["class"].value_counts()
synthetic_class = synthetic_df["class"].value_counts()

comparison = pd.DataFrame({
    "Original": original_class,
    "Synthetic": synthetic_class
}).fillna(0)

print(comparison)

# ============================================================
# 14. CLASS DISTRIBUTION PLOT
# ============================================================

comparison.plot(
    kind="bar",
    figsize=(8, 5)
)

plt.title("Original vs CTGAN Synthetic Class Distribution")
plt.xlabel("Class")
plt.ylabel("Number of Records")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# ============================================================
# 15. AUGMENT ORIGINAL + SYNTHETIC DATA
# ============================================================

augmented_df = pd.concat(
    [df, synthetic_df],
    ignore_index=True
)

print("Original Dataset:", df.shape)
print("Synthetic Dataset:", synthetic_df.shape)
print("Augmented Dataset:", augmented_df.shape)

print("\nAugmented Class Distribution:")
print(augmented_df["class"].value_counts())

augmented_df.to_csv(
    "/content/CKD_CTGAN_Augmented_1000.csv",
    index=False
)

# ============================================================
# 16. PREPARE DATA FOR SMOTE
# ============================================================

smote_df = augmented_df.copy()

# Encode categorical columns
label_encoders = {}

for col in categorical_columns:

    le = LabelEncoder()

    smote_df[col] = le.fit_transform(
        smote_df[col].astype(str)
    )

    label_encoders[col] = le

print(smote_df.head())

# ============================================================
# 17. SEPARATE FEATURES AND TARGET
# ============================================================

X = smote_df.drop("class", axis=1)
y = smote_df["class"]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nBefore SMOTE:")
print(y.value_counts())

# ============================================================
# 18. APPLY SMOTE
# ============================================================

smote = SMOTE(
    random_state=42
)

X_smote, y_smote = smote.fit_resample(
    X,
    y
)

print("After SMOTE:")
print(pd.Series(y_smote).value_counts())

print("\nSMOTE Dataset Shape:")
print(X_smote.shape)

# ============================================================
# 19. CREATE BALANCED DATASET
# ============================================================

balanced_df = pd.DataFrame(
    X_smote,
    columns=X.columns
)

balanced_df["class"] = y_smote

# Put class column in the original position
original_columns = augmented_df.columns.tolist()

balanced_df = balanced_df[
    original_columns
]

print("Balanced Dataset Shape:", balanced_df.shape)

print("\nBalanced Class Distribution:")
print(balanced_df["class"].value_counts())

# ============================================================
# 20. DECODE CATEGORICAL VARIABLES
# ============================================================

for col in categorical_columns:

    le = label_encoders[col]

    balanced_df[col] = balanced_df[col].round().astype(int)

    # Keep values within valid encoder range
    balanced_df[col] = balanced_df[col].clip(
        0,
        len(le.classes_) - 1
    )

    balanced_df[col] = le.inverse_transform(
        balanced_df[col]
    )

print(balanced_df.head())

# ============================================================
# 21. SAVE FINAL BALANCED DATASET
# ============================================================

balanced_df.to_csv(
    "/content/CKD_CTGAN_SMOTE_Balanced.csv",
    index=False
)

print("Final balanced dataset saved successfully.")

# ============================================================
# 22. COMPARE DATASETS
# ============================================================

print("======================================")
print("DATASET COMPARISON")
print("======================================")

print("\nOriginal Dataset")
print("Records:", len(df))
print(df["class"].value_counts())

print("\nCTGAN Synthetic Dataset")
print("Records:", len(synthetic_df))
print(synthetic_df["class"].value_counts())

print("\nAugmented Dataset")
print("Records:", len(augmented_df))
print(augmented_df["class"].value_counts())

print("\nSMOTE Balanced Dataset")
print("Records:", len(balanced_df))
print(balanced_df["class"].value_counts())

# ============================================================
# 23. DATASET SIZE COMPARISON
# ============================================================

dataset_sizes = {
    "Original": len(df),
    "CTGAN Synthetic": len(synthetic_df),
    "Augmented": len(augmented_df),
    "SMOTE Balanced": len(balanced_df)
}

plt.figure(figsize=(9, 5))

plt.bar(
    dataset_sizes.keys(),
    dataset_sizes.values()
)

plt.title("Dataset Size at Different Stages")
plt.xlabel("Dataset")
plt.ylabel("Number of Samples")

plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# ============================================================
# 24. PREPARE FINAL DATA FOR ML
# ============================================================

ml_df = balanced_df.copy()

# Encode categorical features
for col in categorical_columns:

    le = LabelEncoder()

    ml_df[col] = le.fit_transform(
        ml_df[col].astype(str)
    )

# Encode target
target_encoder = LabelEncoder()

ml_df["class"] = target_encoder.fit_transform(
    ml_df["class"]
)

X = ml_df.drop("class", axis=1)
y = ml_df["class"]

print(X.shape)
print(y.value_counts())

# ============================================================
# 25. TRAIN TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

